<?php

namespace Database\Seeders;

use App\Models\Temple;
use Illuminate\Database\Seeder;

class TempleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $temples = [
            [
                'name' => 'Kashi Vishwanath',
                'location' => 'Varanasi, Uttar Pradesh',
                'image' => '/banner/Kashi-temple-1.jpg',
                'rating' => 4.9,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => true,
                'instant_price' => 100,
                'hold_token' => 50,
                'description' => 'One of the holiest temples in Hinduism, dedicated to Lord Shiva. Located on the banks of the Ganges River, it is believed that Lord Shiva performs the final ritual of moksha for those who die here.',
                'amenities' => [
                    'Darshan Available',
                    'Special Pooja Services',
                    'Temple Store',
                    'Prasad Distribution',
                ],
                'timings' => [
                    [
                        'name' => 'Morning Aarti',
                        'time' => '05:00 - 06:00',
                        'type' => 'Regular'
                    ],
                    [
                        'name' => 'Evening Aarti',
                        'time' => '19:00 - 20:00',
                        'type' => 'Regular'
                    ],
                    [
                        'name' => 'Night Aarti',
                        'time' => '21:30 - 22:30',
                        'type' => 'Regular'
                    ],
                ],
                'facilities' => [
                    'Parking',
                    'Restrooms',
                    'Food Courts',
                    'Accommodation',
                    'Lost & Found',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Ram Mandir',
                'location' => 'Ayodhya, Uttar Pradesh',
                'image' => '/banner/Ram_Mandir.jpg',
                'rating' => 4.8,
                'crowd_level' => 'High',
                'has_vip_darshan' => true,
                'instant_price' => 150,
                'hold_token' => 75,
                'description' => 'The newly constructed Ram Mandir is one of the most significant temples in India, dedicated to Lord Rama. This grand structure showcases exquisite architecture and is a pilgrimage destination for millions.',
                'amenities' => [
                    'Darshan Available',
                    'Guided Tours',
                    'Temple Store',
                    'Prasad Distribution',
                ],
                'timings' => [
                    [
                        'name' => 'Morning Aarti',
                        'time' => '06:00 - 07:00',
                        'type' => 'Regular'
                    ],
                    [
                        'name' => 'Evening Aarti',
                        'time' => '18:00 - 19:00',
                        'type' => 'Regular'
                    ],
                ],
                'facilities' => [
                    'Parking',
                    'Restrooms',
                    'Food Courts',
                    'Accommodation',
                    'Wheelchair Access',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Tirupati Balaji',
                'location' => 'Tirupati, Andhra Pradesh',
                'image' => '/banner/tirupati-balaji.jpg',
                'rating' => 4.7,
                'crowd_level' => 'High',
                'has_vip_darshan' => true,
                'instant_price' => 200,
                'hold_token' => 100,
                'description' => 'One of the richest temples in the world, Tirupati Balaji is dedicated to Lord Venkateswara. It attracts millions of pilgrims annually and is known for its elaborate rituals and spiritual significance.',
                'amenities' => [
                    'Darshan Available',
                    'VIP Darshan',
                    'Special Pooja Services',
                    'Temple Store',
                    'Prasad Distribution',
                ],
                'timings' => [
                    [
                        'name' => 'Morning Darshan',
                        'time' => '06:00 - 09:00',
                        'type' => 'Regular'
                    ],
                    [
                        'name' => 'Afternoon Darshan',
                        'time' => '12:00 - 16:00',
                        'type' => 'Regular'
                    ],
                    [
                        'name' => 'Evening Darshan',
                        'time' => '17:00 - 21:00',
                        'type' => 'Regular'
                    ],
                ],
                'facilities' => [
                    'Parking',
                    'Restrooms',
                    'Food Courts',
                    'Accommodation',
                    'Lost & Found',
                    'Wheelchair Access',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Mahakaleswar Jyotirling',
                'location' => 'Ujjain, Madhya Pradesh',
                'image' => '/banner/mahakaleshwar.jpg',
                'rating' => 4.6,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => 80,
                'hold_token' => 40,
                'description' => 'Mahakaleswar Jyotirling is one of the 12 sacred Jyotirlinga temples dedicated to Lord Shiva. The temple has been a major pilgrimage center for centuries and holds immense spiritual significance.',
                'amenities' => [
                    'Darshan Available',
                    'Special Pooja Services',
                    'Temple Store',
                    'Prasad Distribution',
                ],
                'timings' => [
                    [
                        'name' => 'Morning Aarti',
                        'time' => '04:00 - 05:00',
                        'type' => 'Regular'
                    ],
                    [
                        'name' => 'Evening Aarti',
                        'time' => '20:00 - 21:00',
                        'type' => 'Regular'
                    ],
                ],
                'facilities' => [
                    'Parking',
                    'Restrooms',
                    'Food Courts',
                    'Lost & Found',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Vaishno Devi',
                'location' => 'Katra, Jammu & Kashmir',
                'image' => '/banner/vaishano-devi-1.png',
                'rating' => 4.8,
                'crowd_level' => 'Low',
                'has_vip_darshan' => true,
                'instant_price' => 120,
                'hold_token' => 60,
                'description' => 'Vaishno Devi shrine is one of the most visited pilgrimage sites in India, dedicated to Goddess Vaishno Devi. The temple is located in a cave and is accessible through a scenic trekking route.',
                'amenities' => [
                    'Darshan Available',
                    'Guided Tours',
                    'Temple Store',
                    'Prasad Distribution',
                ],
                'timings' => [
                    [
                        'name' => 'Morning Darshan',
                        'time' => '06:00 - 12:00',
                        'type' => 'Regular'
                    ],
                    [
                        'name' => 'Evening Darshan',
                        'time' => '14:00 - 21:00',
                        'type' => 'Regular'
                    ],
                ],
                'facilities' => [
                    'Parking',
                    'Restrooms',
                    'Food Courts',
                    'Accommodation',
                    'Lost & Found',
                    'First Aid',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Shailani Mata Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2025/11/20/1949769-sheetla-mandir2.webp',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Khaliji Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Ram Bhavan',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Sri Siddhi Ganesha Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://maharajji.love/files/images/lucknow-gallery/images/large/13-grounds.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Sai Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_64958ad2235b6.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Tapeshwari Parwati Sewa Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2025/11/20/1949769-sheetla-mandir2.webp',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Hanuman Setu Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Shree%20Hanuman%20Ji..jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shiv Temple in L Park',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'shiv mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Sai Baba Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_64958ad2235b6.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Bhuiyan Devi Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2025/11/20/1949769-sheetla-mandir2.webp',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Hare Shankar Ji',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Sani Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2024/06/09/1743790-whatsappimage2024-06-09at16423459f5695e.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shri Vardani Hanuman Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shani Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2024/06/09/1743790-whatsappimage2024-06-09at16423459f5695e.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Someshwar Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Chaura Mata Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2025/11/20/1949769-sheetla-mandir2.webp',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Mahadev Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shiv Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Munshi Pulia Hanuman Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shanidev Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2024/06/09/1743790-whatsappimage2024-06-09at16423459f5695e.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Baba Tika Ram Das Hanuman Sai Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shri Khatu Shyam Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2024/09/28/1800213-2024-02-282.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shri Akeleshwar Mahadev Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shiv Shakti Dham',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Dakshin Mukhi Hanuman Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shree Koneshwar Mahadev Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://www.amritvichar.com/media-webp/2025-07/pm-shri---%2816%29.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Radha Krishna Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://iskconlucknowup.org/images/gallery/gam2020/1.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Devlok Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Virateshwar Shiv Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shiva Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Buddheshwar Mandir(Temple)',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://www.livelaw.in/h-upload/2025/09/09/1500x900_619560-lucknow-buddheshwar-mahadev-temple.webp',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shiva Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shiv Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Panchmukhi Hanuman Ji Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shiv Ji Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Arya Samaj Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://aryasamajmandirlucknow.org/assets/img/asm-11.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Peela Hanuman Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Parshuram Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Sankat Mochan Hanuman Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://files.yappe.in/place/full/shri-sankat-mochan-hanuman-mandir-i-i-m-road-10375876.webp',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shri Hans Bhakti Dham',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://mindtrip.ai/attractions/d050/1049/0f58/f3df/f01b/95dc/0040/5933',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shri Mahabir Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Maa Sheetla Mata Temple',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/h-upload/2025/11/20/1949769-sheetla-mandir2.webp',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Shree Bholeshwar Mahadev',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://static.newstrack.com/uploads/images/2023/06/image_800x450_649bfd412cad4.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Chuhariya Mata Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://staticimg.amarujala.com/assets/images/4cplus/2026/05/27/chhaharaya-mata-mathara_09d4e6f117b22ce7ad4cddf6927e6c11.jpeg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Hanuman Mandir',
                'location' => 'Lucknow, Uttar Pradesh',
                'image' => 'https://2.bp.blogspot.com/-jMNbYAolslE/WQ8ZFKQpuRI/AAAAAAAAAK0/j3KcWKvJe6QCQNhWKFTdWBEyx-bSOfTMwCLcB/s640/hhhhhhh.jpg',
                'rating' => 4.5,
                'crowd_level' => 'Moderate',
                'has_vip_darshan' => false,
                'instant_price' => null,
                'hold_token' => null,
                'description' => null,
                'amenities' => null,
                'timings' => null,
                'facilities' => null,
                'status' => 'active',
            ],
        ];

        foreach ($temples as $temple) {
            Temple::firstOrCreate(
                ['name' => $temple['name']],
                $temple
            );
        }
    }
}