<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class GuideController extends Controller
{
    public function index()
    {
        // Sample guide data
    $guides = [
    [
        'id' => 1,
        'name' => 'Pandit Rajesh Sharma',
        'category' => 'Temple Guide',
        'specialization' => 'Vedic Rituals & Temple History',
        'image' => '/banner/guide-1.jpg',
        'image_style' => 'width: 100%; height: 250px; object-fit: cover; object-position: center;',
        'rating' => 4.9,
        'reviews' => 127,
        'price' => 500,
        'description' => 'Expert temple guide with deep knowledge of Vedic rituals, temple history, and spiritual practices.',
        'languages' => 'Hindi, English, Sanskrit',
        'experience' => '15yr exp',
    ],
    [
        'id' => 2,
        'name' => 'Suresh Kumar',
        'category' => 'Elderly Care',
        'specialization' => 'Senior Temple Visits',
        'image' => '/banner/guide-2.jpg',
        'image_style' => 'width: 100%; height: 250px; object-fit: cover; object-position: center;',
        'rating' => 4.8,
        'reviews' => 89,
        'price' => 400,
        'description' => 'Dedicated elderly care assistant specializing in comfortable temple visits for senior citizens.',
        'languages' => 'Hindi, English, Telugu',
        'experience' => '8yr exp',
    ],
    [
        'id' => 3,
        'name' => 'Priya Menon',
        'category' => 'Translator',
        'specialization' => 'Multilingual Communication',
        'image' => '/banner/guide-3.jpg',
        'image_style' => 'width: 100%; height: 250px; object-fit: cover; object-position: top;',
        'rating' => 4.7,
        'reviews' => 64,
        'price' => 350,
        'description' => 'Multilingual translator fluent in 5 Indian languages. Bridges communication gaps for pilgrims.',
        'languages' => 'English, Hindi, Tamil, Kannada, Malayalam',
        'experience' => '6yr exp',
    ],
    [
        'id' => 4,
        'name' => 'Vikram Singh',
        'category' => 'Family Coordinator',
        'specialization' => 'Group Management',
        'image' => '/banner/guide-4.jpg',
        'image_style' => 'width: 100%; height: 250px; object-fit: cover; object-position: center;',
        'rating' => 4.6,
        'reviews' => 52,
        'price' => 600,
        'description' => 'Family pilgrimage coordinator managing group trips with children and elders. Handles logistics and timing.',
        'languages' => 'Hindi, English, Punjabi',
        'experience' => '12yr exp',
    ],
    [
        'id' => 5,
        'name' => 'Acharya Deepak Tiwari',
        'category' => 'Temple Guide',
        'specialization' => 'Spiritual Guidance',
        'image' => '/banner/guide-5.jpg',
        'image_style' => 'width: 100%; height: 250px; object-fit: cover; object-position: center;',
        'rating' => 4.9,
        'reviews' => 203,
        'price' => 750,
        'description' => 'Senior temple scholar with 22 years of experience in Mahakaleshwar and Varanasi temples.',
        'languages' => 'Hindi, English, Sanskrit',
        'experience' => '22yr exp',
    ],
    [
        'id' => 6,
        'name' => 'Meera Devi',
        'category' => 'Elderly Care',
        'specialization' => 'Nursing & Support',
        'image' => '/banner/guide-6.jpg',
        'image_style' => 'width: 100%; height: 250px; object-fit: cover; object-position: top;',
        'rating' => 4.8,
        'reviews' => 76,
        'price' => 450,
        'description' => 'Compassionate elderly care specialist with nursing background. Ensures comfortable temple visits.',
        'languages' => 'Hindi, English, Bhojpuri',
        'experience' => '12yr exp',
    ]
];

        return Inertia::render('Temple/Guide', [
            'guides' => $guides,
        ]);
    }

    public function show($id)
    {
        // Sample guide profile data
        $guides = [
            1 => [
                'id' => 1,
                'name' => 'Pandit Rajesh Sharma',
                'category' => 'Temple Guide',
                'specialization' => 'Vedic Rituals & Temple History',
                'image' => '/banner/guide-1.jpg',
                'rating' => 4.9,
                'reviews' => 127,
                'price' => 500,
                'description' => 'Expert temple guide with deep knowledge of Vedic rituals, temple history, and spiritual practices.',
                'longDescription' => 'With over 15 years of experience guiding pilgrims through India\'s most sacred temples, I provide comprehensive knowledge about temple history, spiritual significance, and ritual practices. I specialize in explaining the philosophical and spiritual aspects of Hindu rituals, making them accessible to all pilgrims regardless of their background.',
                'languages' => ['Hindi', 'English', 'Sanskrit'],
                'experience' => '15 years',
                'verified' => true,
                'availability' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                'hourlyRate' => 500,
                'groupRate' => 4500,
                'maxGroupSize' => 15,
            ],
            2 => [
                'id' => 2,
                'name' => 'Suresh Kumar',
                'category' => 'Elderly Care',
                'specialization' => 'Senior Temple Visits',
                'image' => '/banner/guide-2.jpg',
                'rating' => 4.8,
                'reviews' => 89,
                'price' => 400,
                'description' => 'Dedicated elderly care assistant specializing in comfortable temple visits for senior citizens.',
                'longDescription' => 'I am a compassionate caregiver with 8 years of experience assisting seniors during their spiritual journeys. I ensure comfort, safety, and accessibility throughout temple visits, handling logistics and providing personal care support when needed.',
                'languages' => ['Hindi', 'English', 'Telugu'],
                'experience' => '8 years',
                'verified' => true,
                'availability' => ['Tuesday', 'Wednesday', 'Thursday', 'Saturday', 'Sunday'],
                'hourlyRate' => 400,
                'groupRate' => 3500,
                'maxGroupSize' => 10,
            ],
            3 => [
                'id' => 3,
                'name' => 'Priya Menon',
                'category' => 'Translator',
                'specialization' => 'Multilingual Communication',
                'image' => '/banner/guide-3.jpg',
                'rating' => 4.7,
                'reviews' => 64,
                'price' => 350,
                'description' => 'Multilingual translator fluent in 5 Indian languages. Bridges communication gaps for pilgrims from different regions.',
                'longDescription' => 'As a professional multilingual translator with 6 years of experience in temple tourism, I bridge the communication gap for pilgrims from different regions. I provide accurate translations of rituals, temple significance, and spiritual teachings.',
                'languages' => ['English', 'Hindi', 'Tamil', 'Kannada', 'Malayalam'],
                'experience' => '6 years',
                'verified' => true,
                'availability' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'hourlyRate' => 350,
                'groupRate' => 3000,
                'maxGroupSize' => 20,
            ],
            4 => [
                'id' => 4,
                'name' => 'Vikram Singh',
                'category' => 'Family Coordinator',
                'specialization' => 'Group Management',
                'image' => '/banner/guide-4.jpg',
                'rating' => 4.6,
                'reviews' => 52,
                'price' => 600,
                'description' => 'Family pilgrimage coordinator managing group trips with children and elders. Handles logistics and timing.',
                'longDescription' => 'With 12 years of experience coordinating family pilgrimages, I excel at managing diverse groups with different needs. I coordinate schedules, manage timings, and ensure everyone\'s comfort throughout the journey.',
                'languages' => ['Hindi', 'English', 'Punjabi'],
                'experience' => '12 years',
                'verified' => true,
                'availability' => ['Monday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'hourlyRate' => 600,
                'groupRate' => 5500,
                'maxGroupSize' => 25,
            ],
            5 => [
                'id' => 5,
                'name' => 'Acharya Deepak Tiwari',
                'category' => 'Temple Guide',
                'specialization' => 'Spiritual Guidance',
                'image' => '/banner/guide-5.jpg',
                'rating' => 4.9,
                'reviews' => 203,
                'price' => 750,
                'description' => 'Senior temple scholar with 22 years of experience in Mahakaleshwar and Varanasi temples.',
                'longDescription' => 'As a senior temple scholar with 22 years of experience, I provide in-depth spiritual guidance and philosophical teachings. My expertise in Shiva worship and tantric practices offers pilgrims a unique, transformative experience.',
                'languages' => ['Hindi', 'English', 'Sanskrit'],
                'experience' => '22 years',
                'verified' => true,
                'availability' => ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                'hourlyRate' => 750,
                'groupRate' => 6500,
                'maxGroupSize' => 15,
            ],
            6 => [
                'id' => 6,
                'name' => 'Meera Devi',
                'category' => 'Elderly Care',
                'specialization' => 'Nursing & Support',
                'image' => '/banner/guide-6.jpg',
                'rating' => 4.8,
                'reviews' => 76,
                'price' => 450,
                'description' => 'Compassionate elderly care specialist with nursing background. Ensures comfortable temple visits.',
                'longDescription' => 'I am a trained nurse with 12 years of experience providing specialized care for elderly pilgrims. I combine medical knowledge with spiritual sensitivity to ensure safe, comfortable, and meaningful temple experiences.',
                'languages' => ['Hindi', 'English', 'Bhojpuri'],
                'experience' => '12 years',
                'verified' => true,
                'availability' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                'hourlyRate' => 450,
                'groupRate' => 4000,
                'maxGroupSize' => 12,
            ],
        ];

        $guide = $guides[$id] ?? $guides[1];

        return Inertia::render('Temple/GuideProfile', [
            'guide' => $guide,
        ]);
    }
}
