<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class TransportController extends Controller
{
    public function index()
    {
        $transports = [
            [
                'id' => 1,
                'name' => 'Ram Mandir Express Shuttle',
                'location' => 'Ram Mandir',
                'type' => 'Shuttle',
                'image' => '/banner/bus-1.jpg',
                'from' => 'Ayodhya Railway Station',
                'to' => 'Ram Mandir Main Gate',
                'duration' => '15 min',
                'seats' => 40,
                'frequency' => 'Every 10 min',
                'price' => 30,
                'amenities' => ['AC', 'GPS Tracking', 'WiFi'],
                'status' => 'Available Now',
                'available' => true,
            ],
            [
                'id' => 2,
                'name' => 'Varanasi Ghat Auto Service',
                'location' => 'Kashi Vishwanath',
                'type' => 'Auto',
                'image' => '/banner/bus-2.jpg',
                'from' => 'Varanasi Cantt Station',
                'to' => 'Kashi Vishwanath Temple',
                'duration' => '25 min',
                'seats' => 3,
                'frequency' => 'On demand',
                'price' => 80,
                'amenities' => ['GPS Tracking'],
                'status' => 'Available Now',
                'available' => true,
            ],
            [
                'id' => 3,
                'name' => 'Tirupati Premium Taxi',
                'location' => 'Tirupati Balaji',
                'type' => 'Taxi',
                'image' => '/banner/bus-3.jpg',
                'from' => 'Tirupati Railway Station',
                'to' => 'Tirumala Temple Hill Top',
                'duration' => '45 min',
                'seats' => 4,
                'frequency' => 'On demand',
                'price' => 450,
                'amenities' => ['AC', 'GPS Tracking', 'Safety Kit'],
                'status' => 'Available Now',
                'available' => true,
            ],
            [
                'id' => 4,
                'name' => 'Ujjain City Bus',
                'location' => 'Mahakaleshwar Jyotiringa',
                'type' => 'Bus',
                'image' => '/banner/bus-4.jpg',
                'from' => 'Ujjain Central Bus Stand',
                'to' => 'Mahakaleshwar Temple',
                'duration' => '20 min',
                'seats' => 50,
                'frequency' => 'Every 15 min',
                'price' => 15,
                'amenities' => ['AC', 'WiFi'],
                'status' => 'Available Now',
                'available' => true,
            ],
            [
                'id' => 5,
                'name' => 'Katra Helicopter Shuttle',
                'location' => 'Vaishno Devi',
                'type' => 'Shuttle',
                'image' => '/banner/bus-5.jpg',
                'from' => 'Katra Helipad',
                'to' => 'Vaishno Devi Bhawan',
                'duration' => '8 min',
                'seats' => 6,
                'frequency' => 'Every 30 min',
                'price' => 1800,
                'amenities' => ['Safety Kit', 'GPS Tracking'],
                'status' => 'Available Now',
                'available' => true,
            ],
            [
                'id' => 6,
                'name' => 'Ayodhya City Auto',
                'location' => 'Ram Mandir',
                'type' => 'Auto',
                'image' => '/banner/bus-6.jpg',
                'from' => 'Ayodhya Bus Stand',
                'to' => 'Ram Mandir Gate 2',
                'duration' => '10 min',
                'seats' => 3,
                'frequency' => 'On demand',
                'price' => 50,
                'amenities' => ['GPS Tracking', 'Fast Route'],
                'status' => 'Available Now',
                'available' => true,
            ],
            [
                'id' => 7,
                'name' => 'Tirupati Hilltop AC Bus',
                'location' => 'Tirupati Balaji',
                'type' => 'Bus',
                'image' => '/banner/bus-7.jpg',
                'from' => 'Tirupati APSRTC Bus Stand',
                'to' => 'Tirumala Bus Stand',
                'duration' => '35 min',
                'seats' => 45,
                'frequency' => 'Every 5 min',
                'price' => 75,
                'amenities' => ['AC', 'WiFi'],
                'status' => 'Available Now',
                'available' => true,
            ],
        ];

        return Inertia::render('Temple/Transport', [
            'transports' => $transports,
        ]);
    }
}
